### ISSUE TITLE
Release dcw 2.2.0

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#103]
**Version**:  2.2.0

**Scheduled date**: 21 JUN, 2024

**Before release**:

- [x] Check the [changelog](https://github.com/GenericMappingTools/dcw-gmt/blob/master/ChangeLog).
- [x] Check the settings in [config.mk](https://github.com/GenericMappingTools/dcw-gmt/blob/master/config.mk).
  - [x] `GMT_VERSION` sets the correct minimum required GMT version.
  - [x] `DCW_VERSION` sets the correct version of DCW to be released.
  - [x] `DCW_DATE` sets the correct release date.
- [x] Run `make spotless` to clear out any old distribution files.
- [x] Run `make all` to make the dcw-gmt.nc file, create the tarball and zipfile, compute the MD5 checksum of the tarball, and create the dcw figure.

**Release**

- [x] Create a new [GitHub release](https://github.com/GenericMappingTools/dcw-gmt/releases).
  - [x] Upload the tarball.
  - [x] Add a description to the release.
  - [x] Add the MD5 checksum and sha256sum to the release notes.
- [x] Run `make update-dataserver` to update the files on the GMT server using the GitHub release (@Esteban82).
- [x] Update the dcw version in the [downloads](https://github.com/GenericMappingTools/website/blob/master/download/index.rst) section of the website.

**3rd-party update**

**More volunteers needed!** Please let us know if you volunteer to help to maintain dcw-gmt in these 3rd-party tools.

- [x] Update [conda-forge feedstock](https://github.com/conda-forge/dcw-gmt-feedstock) (@seisman) https://github.com/conda-forge/dcw-gmt-feedstock/pull/13
- [x] Update [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gmt.rb) (@seisman) https://github.com/Homebrew/homebrew-core/pull/176668
- [ ] Update the builtin dcw-gmt version in the Windows installers (@joa-quim)

**Comment by seisman** [comment]
i also have no experience doing this.

**Comment by joa-quim** [comment]
Me neither 😀

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Dongdong Tian ***@***.***>
Enviado: Friday, June 21, 2024 3:51:02 PM
Para: GenericMappingTools/dcw-gmt ***@***.***>
Cc: Joaquim Manuel Freire Luís ***@***.***>; Mention ***@***.***>
Assunto: Re: [GenericMappingTools/dcw-gmt] Release dcw 2.2.0 (Issue #103)


i also have no experience doing this.

**Comment by Esteban82** [comment]
Ok. No problem. Maybe max has experience. 

I think that the changelog is ok.

**Comment by Esteban82** [comment]
I can't enter the server (`gmtserver.soest.hawaii.edu`). Can you?

**Comment by joa-quim** [comment]
Yes, no problems here.

**Comment by joa-quim** [comment]
> to place the tarball on the gmt ftp

Should we drop this from our recipes?

**Comment by Esteban82** [comment]
> Should we drop this from our recipes?

What is that? The server for this website (https://www.soest.hawaii.edu/pwessel/dcw/)?

**Comment by Esteban82** [comment]
I am not very clear about all the options for users to access this data. Where is the data download from when they do not have it on their pc?

**Comment by joa-quim** [comment]
> What is that? The server for this website (https://www.soest.hawaii.edu/pwessel/dcw/)?

Yes, for obvious reasons

DCW files are in

https://github.com/GenericMappingTools/dcw-gmt/releases

**Comment by Esteban82** [comment]
> Yes, for obvious reasons

I agree.

**Comment by Esteban82** [comment]
> DCW files are in
> 
> https://github.com/GenericMappingTools/dcw-gmt/releases

And also here: https://oceania.generic-mapping-tools.org/geography/dcw/ and in zenodo (I did this)

**Comment by anbj** [comment]
> > DCW files are in
> > https://github.com/GenericMappingTools/dcw-gmt/releases
> 
> And also here: https://oceania.generic-mapping-tools.org/geography/dcw/ and in zenodo (I did this)

Are those files on oceania always up-to-date, i.e. the latest release?

And regarding ftp, I really don’t think it should be necessary. Ftp is obsolete, outdated and older than the internet (or something like that).

**Comment by Esteban82** [comment]
I made a draft of the release (I still have to add the files). I don't understand well what GMT minimum version we need (6.1.1 or 6.4).

https://github.com/GenericMappingTools/dcw-gmt/releases/tag/untagged-b63788cf64b7e390dbaf

**Comment by Esteban82** [comment]
> Are those files on oceania always up-to-date, i.e. the latest release?

I would have to check but I think so.

**Comment by seisman** [comment]
> I made a draft of the release (I still have to add the files). I don't understand well what GMT minimum version we need (6.1.1 or 6.4).
> 
> https://github.com/GenericMappingTools/dcw-gmt/releases/tag/untagged-b63788cf64b7e390dbaf

The minimum required GMT version is still 6.1.1.

It seems the DCW_DATE in `config.mk` is not updated yet.

**Comment by Esteban82** [comment]
> The minimum required GMT version is still 6.1.1.

Ok, thanks for the clarification.

> It seems the DCW_DATE in `config.mk` is not updated yet.

It is updated in my local file.

**Comment by Esteban82** [comment]
I uploaded the files to the draft. 

I run `make update-dataserver` but I cannot enter the server.

**Comment by seisman** [comment]
I can log in the data server. Any errors you're having?

**Comment by Esteban82** [comment]
I don't know well. I don't seem to be authorized. I'm pretty sure I got my password right. By the way, this week I reinstalled the operating system (to ubuntu 24.04).

```
ssh esteban82@gmtserver.SOEST.Hawaii.edu
esteban82@gmtserver.soest.hawaii.edu's password: 
Permission denied, please try again.
```

**Comment by seisman** [comment]
On the data server, I can see:
```
drwxr-xr-x  2 meghanj       gmt          6 Aug 11  2022 esteban82
```
For unknown reasons, the `esteban82` directory's owner is `meghanj`. It's likely the reason that you can't log in the server. Maybe @maxrjones knows why it happens?

**Comment by Esteban82** [comment]
Ok, let's wait.

**Comment by Esteban82** [comment]
> I can log in the data server. Any errors you're having?

I managed to enter from the pc of my office. I don't know why it worked.

**Comment by Esteban82** [comment]
I will publish the new release. I hope everything is fine.

**Comment by Esteban82** [comment]
I update directly to master the [changelog](https://github.com/GenericMappingTools/dcw-gmt/blob/master/ChangeLog) and in the [downloads](https://github.com/GenericMappingTools/website/blob/master/download/index.rst) section of the website.

**Comment by Esteban82** [comment]
> I updated directly to master the [changelog](https://github.com/GenericMappingTools/dcw-gmt/blob/master/ChangeLog) and in the [downloads](https://github.com/GenericMappingTools/website/blob/master/download/index.rst) section of the website.

**Comment by Esteban82** [comment]
I think it went well. If someone could test it, it would be great.

**Comment by seisman** [comment]
Just want to make sure that we are going to abandon the FTP site, since no one has the permission to upload files to the site?

**Comment by Esteban82** [comment]
> Just want to make sure that we are going to abandon the FTP site, since no one has the permission to upload files to the site?

Maybe Max has permission to upload the files. 

But I agree that we should abandon the FPT site. We could post all the relevant information in the readme of this repo.

**Comment by joa-quim** [comment]
Yes, I agree that the idea here is to abandon the hawaiian ftp altogether, regardless of we (still) have permission to upload files there.

**Comment by seisman** [comment]
The homebrew formula has been updated. Ping @joa-quim to update the dcw data in the Windows installers, then this released should be finished.
