### ISSUE TITLE
DCW 2.0.0 will cause troubles for homebrew and macports

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/dcw-gmt#13]
Hombrew provides both GMT 5.4.5 and GMT 6 latest, and macports provides GMT 4.5.18, 5.4.5 and 6 latest.

When we release DCW 2.0.0, Homebrew and macports can't upgrade their DCW package from 1.1.4 to 2.0.0. If they do, GMT 4 and GMT5 will break, unless they maintain a separate package for DCW 2.x.

**Comment by PaulWessel** [comment]
Seems their recipes for the old versions need to specify dcw 1.1.4 while the latest can specify 2.0.0. Yes, they would need to maintain separate packages if they also need to maintain old GMT stuff.

**Comment by nieder** [comment]
Don't know what Macports and homebrew will do, but if 2.0.0 will not be backwards compatible, Fink will just put it into a new prefix (such as %p/share/gmt/dcw2). Then any new gmt library versions can be told to look there and our legacy packages gmt4/5/6 can keep using the old one in share/gmt/dcw. This will hit any packager that keeps multiple libraries, not just the macOS trio.
