### ISSUE TITLE
Add Oceans and Sea of IHO for DCW 2.1.0

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#18]
### Idea
I think that would be great to add polygons (with a code) for the oceans and seas. This way I could a make a map of the  Mediterranean Sea (MS) with a code like -R=MS (or -R=MediterraneanSea). 

### Proposal

We could follow "Limits of Oceans and Seas" of the International Hydrographic Organization (1953) to avoid any definitions or naming issue. There is a draft for the a new version but it is not official yet.

The limits of IHO (1953) were digitized (in [shp fles](https://www6.rennes.inrae.fr/ese_eng/Media/Fichier/HRMLOS-shapfile)) and adapted to the GSHHS by Fourcy and Lorvelec (2013). In its [website](https://www6.rennes.inrae.fr/ese_eng/HRMLOS) they said that: "This map is freely available for non-commercial use".

The shp file (153,8 MB) contains 105 objects but are many polygons that correspond to sub-divisions (like all the seas of the Mediterranean) and sub-sub-divisions that we could exclude (or not). Or maybe include just some of the same (like the states of the larger countries). 

The main divisions are only 9/10 (see southern ocean below).

1. North Atlantic Ocean
2. Baltic Sea
3. Mediterranean region
4. South Atlantic Ocean
5. Indian Ocean
6. South China & Eastern Archipelagic seas
7. North Pacific Ocean
8. South Pacific Ocean
9. Arctic Ocean
10. Southern Ocean

Here is a map from the shp file:
![Oceans3](https://user-images.githubusercontent.com/17908951/132728002-5a74bc96-d30d-4877-8f07-e0d811d96e90.png)

`gmt plot -Rd -JW15c HRmLOS_1.1.shp -Bf -png Oceans3 -Gdodgerblue2 -W`

### Souther Ocean
The main issue would be the [southern ocean](https://en.wikipedia.org/wiki/Southern_Ocean) which: "The IHO included the ocean and its definition as the waters south of the 60th parallel south in its 2000 revisions, but this has not been formally adopted, due to continuing impasses about some of the content, such as the naming dispute over the Sea of Japan."
For example, [here in the NOAA](https://www.ngdc.noaa.gov/mgg/global/etopo1_ocean_volumes.html) it was included.

### References and source

* "Limits of Oceans and Seas, 3rd edition" (PDF). International Hydrographic Organization. 1953. [Link](https://iho.int/uploads/user/pubs/standards/s-23/S-23_Ed3_1953_EN.pdf)
* Fourcy, Damien; Lorvelec, Olivier (2013). "A New Digital Map of Limits of Oceans and Seas Consistent with High-Resolution Global Shorelines". Journal of Coastal Research. 29 (2): 471–477. doi:10.2112/JCOASTRES-D-12-00079.1. [Researchgate Link](https://www.researchgate.net/publication/260104508_A_New_Digital_Map_of_Limits_of_Oceans_and_Seas_Consistent_with_High-Resolution_Global_Shorelines)

**Comment by PaulWessel** [comment]
Good ideas.  However, since in the end **-R** takes a w/e/s/n and not a polygon, is it enough to associate these new codes with the enclosing rectangular w/e/s/n?

**Comment by Esteban82** [comment]
Yes, my original idea it to get the enclosing rectangular w/e/s/n. 

Maybe later we could add the polygons so the areas could be plot similar for the countries.

**Comment by PaulWessel** [comment]
The implementation of this would be a table of codes for the oceans and a corresponding w e s n.  Then the gmtinit_parse_R_option would check if we get one of those (just like we do for -Rg -Rd) and substitute the region.  So none of that would go into dcw I think, just gmt.

**Comment by Esteban82** [comment]
Ok. So should I close this issue and open another in gmt? 

By the way, I can't find any codes for the oceans. Should we create them? Maybe we could have both, a 2-3 letters code and a long/full name?

**Comment by PaulWessel** [comment]
I think some shorthand for the worlds oceans is a good idea, and we can try to give them code and long names.  Since this is not DCW related there is no need to think 2-character "pseudo-ISO" codes. While we dont want to maintain a list of 100s of such names and codes, I can imagine some users would like to have similar codes for land areas, e.g., "MiddleEast", "Balkans", "Scandinavia", for a carefully selected -R value.  So please start a GMT feature request and make a proposal that we can discuss further,

**Comment by Esteban82** [comment]
Ok.
