### ISSUE TITLE
DCW 2.0.1 requires GMT 6.3

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/dcw-gmt#25]
The dcw patch release bumped the required GMT version from 6.1.1 to 6.3.0. Was this intentional? If so, we should update the documentation. If not, we should submit another patch release so that 6.1.1 - 6.2.0 can still use dcw with the latest changes.

**Comment by PaulWessel** [comment]
I think that was a mistake.  6.1.1 to 6.3.0 should be it.

**Comment by Esteban82** [comment]
Can be closed? 
Should I be able to close it? (Because I can't).

**Comment by meghanrjones** [comment]
The CI workflows for PyGMT are broken due to this restriction. I think this will be the case for anyone installing GMT 6.2.0 through conda without pinning dcw to 2.0.0. Unless 2.1.0 is planned soon, I think it might be worth having a patch release 2.0.2 to fix GMT 6.1.1 - 6.2.0 installations that auto download the latest dcw.

**Comment by PaulWessel** [comment]
We were thinking of doing 2.0.2 that just has a few polygon fixes and groups, and do the collections.txt stuff in 2.1.  Perhaps that is now a better plan due to the Python issue?

**Comment by meghanrjones** [comment]
Yes, I think so. Note it's not unique to Python. For example, using conda to install 6.2 with `conda install gmt=6.2 -c conda-forge` would also not work for modules that use dcw.
