### ISSUE TITLE
Include countries within Great Britain? 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#30]
Should we include the divisions of GB? England, Scotland, Wales, Northern Ireland? 

I don't know if there is a similar case where we could include internal sub-divisions.

**Comment by PaulWessel** [comment]
I think not.  That opens it up to lots of other similar cases I think.  We can instead consider user feedback once this feature is available and if we really need to add a few more than we can do it later, but not in v1.0.

**Comment by Esteban82** [comment]
Ok. Fine by me. 

Although I do not follow what you said about v1.0. I was thinking those countries in the same way that the internal subdivision of others countries (like CA, US, AR, BR, RU, CN, IN,  AU) are included. But yes, we can wait until someone ask for it.

**Comment by PaulWessel** [comment]
By 1.0 I meant DCW 2.0.2!

**Comment by Esteban82** [comment]
Ok. I am closing this.

**Comment by Esteban82** [comment]
I run the following code. `GB.txt` already have the limits between England, Wales and Scotland. 


`gmt coast -EGB+gred+p -W -png UK -RGB`

![UK](https://user-images.githubusercontent.com/17908951/150910442-83e5034c-21ce-4528-be1a-028282e59a47.png)

**Comment by Esteban82** [comment]
@anbj would you like to fix also this?

**Comment by anbj** [comment]
I may, but have to take a look. Alot of small islands and stuff.

I think we're mixing different concepts (states (US), fylke (NO), etc.), but I guess that's OK; the point being that we want to be able to depict administrative boundaries below the 'main level'.

**Comment by joa-quim** [comment]
Sorry, but I am not favorable to expanding the DCW datset. There are lots of countries in the world and we are not going to add administrative provinces for them all. We have GADM for that. What I would like to have is a tiny version (only a couple of MB) with all country polygons.

**Comment by Esteban82** [comment]
Ok, then we should probably delete the boundaries between Scotland-England and Wales-England.

**Comment by seisman** [comment]
I also agree with @joa-quim. 

We probably should have a new version of dataset using OpenStreetMap instead, although it needs more work.

**Comment by joa-quim** [comment]
I know that we are not consistent in what countries have/have not internal subdivisions but we don't want to change that too because that would be a backward compatibility break. The DCW in itself is not a good product. Many borders between countries are not described equally by the two neighbor polygons.

**Comment by anbj** [comment]
Yes, I saw that in #100; the boundary DE-PL does not align.

DCW may not be a 'good product', but it is very useful.

And what's the plan for a better solution with GADM/OpenStreetMap?

Please share if you have a nice workflow of getting/processing GADM/OpenStreetMap, @joa-quim.

**Comment by joa-quim** [comment]
For now, the only nice workflow I have to access GADM is with GMT.jl See [here](http://fct-gmt.ualg.pt/GMTjl_doc/examples/misc/gadm/) (you may have certificate  issues but the official docs did not build this example likely dues to internet troubles). And beware that GADM data license does not allow redistribution. Don't know if OpenStreetMap has country borders.

**Comment by joa-quim** [comment]
> Are you saying that we should not erase the internal divisions within the island of Great Britain?

Yes, for the reason I mentioned above.

And it looks that we don't even have polygons for Scotland or Wales. But the UK is such a mess that that don't know what is right to have or not.
```
C:\v>pscoast -E+l | grep SC
SC      Seychelles

C:\v>pscoast -E+l | grep WA
```

**Comment by Esteban82** [comment]
You can use GADM data with 


```
URL=https://geodata.ucdavis.edu/gadm/gadm4.1/kmz/gadm41_BRA_1.kmz
gmt begin Brasil_kml png
   ogr2ogr -f "GMT" gadm41_BRA_1.gmt gadm41_BRA_1.kmz
   gmt plot gadm41_BRA_1.gmt -Wblue -Ra -JM15c -Baf
gmt end show
```

**Comment by joa-quim** [comment]
BTW the country code of `Seychelles` is wrong. It's not `SC` but `SE`

**Comment by anbj** [comment]
Sure? https://en.wikipedia.org/wiki/ISO_3166-2:SC

**Comment by Esteban82** [comment]
> And it looks that we don't even have polygons for Scotland or Wales. But the UK is such a mess that that don't know what is right to have or not.

That is my point. UK level 0 data also includes level 1 data.

**Comment by joa-quim** [comment]
Hmm I found it here https://docs.dnb.com/partner/en-US/iso_country_codes

**Comment by joa-quim** [comment]
Is UK and GB the same thing?
https://www.dictionary.com/e/great-britain-vs-uk-vs-england/

A mess that I don't want to go into, not even read till the end.

**Comment by Esteban82** [comment]
> For now, the only nice workflow I have to access GADM is with GMT.jl

Would be a good idea to make a (supplemental?) module to access the GADM data?

**Comment by joa-quim** [comment]
I also found this one https://www.iban.com/country-codes confirming that Seychelles code is `SC`

Given all this mess, I changed my mind I'm not against making one exception to add level 1 data to GBUK. That would make our already de facto situation be more clear and correct and at same time not increase the DCW file size.

**Comment by joa-quim** [comment]
>Would be a good idea to make a (supplemental?) module to access the GADM data?

Maybe, but who would do it?

**Comment by Esteban82** [comment]
> Maybe, but who would do it?

I could try with some guidance.

**Comment by joa-quim** [comment]
Good to hear that but it would be far from trivial. To be honest I'm not even _visualizing_ what that tool would do. If I think in translating to C what the GMT.jl does with all calls to GDAL functions that it uses ... no thanks.

You guys know that IMO the evolution of GMT is through the wrappers. It's incredibly more productive to write extensions in Julia (and the Py guys will say the same) than suffering weeks (if even doable) to do the same in C.

**Comment by anbj** [comment]
Would it not be easy to build a script that basically uses GADM data instead of DCW data? Since the GADM data license does not allow redistribution, we cannot bundle it with GMT, but we could include a small script that would build it.

**Comment by joa-quim** [comment]
Yes I agree, but remember that we have to use DCW data for that, not GDAM (or any other high resolution data).

**Comment by Esteban82** [comment]
This is how should the map look now. Here GB without internal divisions

```
gmt begin UK png
    gmt coast -W -RGB
    gmt plot GB.txt  -Wthin,black -Ggray
gmt end
```
![UK](https://github.com/GenericMappingTools/dcw-gmt/assets/17908951/5df01814-4dda-4a74-a070-fb80ff4d7589)

**Comment by Esteban82** [comment]
And here the level 1 (England, Northern Ireland, Scotland, Wales).
```
gmt begin UK png
    gmt coast -W -RGB
    gmt plot ENG.txt -Wthin,black -Ggray
    gmt plot NIR.txt -Wthin,orange -Ggreen
    gmt plot SCT.txt -Wthin,blue -Gpink
    gmt plot WLS.txt -Wthin,green -Gblue
gmt end
```

![UK](https://github.com/GenericMappingTools/dcw-gmt/assets/17908951/386f54b0-ae87-4d53-aeca-7bcd9872b90b)
