### ISSUE TITLE
Error in Russia. 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#33]
Some islands of RU.ARK (in red@50) are not included in RU (in blue@50). 

I already have the new RU.txt. Later I will make the PR. This new PR should be dcw 2.0.2? 
Also, there is an smaller bug in the coast. Tomorrow I will try to fix it. 

`gmt coast -RRU.ARK -W -Df -png Rusia -B -JQ15c -ERU.ARK+gred@50 -ERU+gblue@50`

![Rusia](https://user-images.githubusercontent.com/17908951/144960314-30b9f692-0e48-4975-9c58-b9286167d85b.png)

**Comment by PaulWessel** [comment]
Thanks, and yes next will be 2.0.2. Not clear if this is GSHHG or DCW issue - compare to Google Images.

**Comment by Esteban82** [comment]
It is an error in RU.txt. I check it.

**Comment by Esteban82** [comment]
I have a doubt. How create a new version of DCW from the files reformat as suggested. How can I test it on my pc? Is it explain somewhere?

**Comment by PaulWessel** [comment]
I usually type

`make help`

in the top directory which will show up various options.  Stay away from the place-* commands since you do not have permission to write to my FTP site.

**Comment by Esteban82** [comment]
BTW, I `make tig` and I get this figure where only the countries with internal info (states, provinecs, etc) are plotted. At least the island that a I in Russia were plotted. 


![dcw-figure](https://user-images.githubusercontent.com/17908951/145569494-74d60ead-7b58-48e6-a964-89a089cb27c0.png)

**Comment by Esteban82** [comment]
I managed to get the figure from dcw-figure.sh using:
` gmt makecpt -T0/540/1 -Ccategorical -N > /tmp/$$.cpt` instead of 
`gmt makecpt -T0/$n_poly/1 -Ccategorical -N > /tmp/$$.cpt`

I think that there is an error in  n_poly=`gmt info -Fi -o2 /tmp/$$.C.txt`. Its result is 0. It is possible that `gmt info` doesn't count text?
