### ISSUE TITLE
Error in make cheksum?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#36]
After creating a new dcw local vresion I run `make checksum` and I got this error: `md5sum: option incorrect -- «r»`

Then I look in md5sum --help and I didn't see the option -r. 

I try again without -r and I got the following: 

```
md5sum dcw-gmt-2.0.1.tar.gz | awk '{printf "Update dcw-gmt.info with the new check sum: %s\n", $1}'
Update dcw-gmt.info with the new check sum: 923ace8dc72174b4f3da176e5db6f73b
```
Is it a but? Should I remove `-r` in `Makefile`?

**Comment by PaulWessel** [comment]
Unfortunately, on macOS the utility is called md5 while on Linux it is called md5sum.  I have now installed md5sum via mac ports so you can replace md5 with md5sum (and remove the -r).

**Comment by Esteban82** [comment]
Ok. It already says md5sum. I think you had make an alias.
