### ISSUE TITLE
Release dcw 2.0.2

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/dcw-gmt#39]
**Version**:  2.0.2

**Scheduled date**: XXX XX, 20XX

**Before release**:

- [x] Check the [changelog](https://github.com/GenericMappingTools/dcw-gmt/blob/master/ChangeLog).
- [x] Check the settings in [config.mk](https://github.com/GenericMappingTools/dcw-gmt/blob/master/config.mk).
  - [x] `GMT_VERSION` sets the correct minimum required GMT version.
  - [x] `DCW_VERSION` sets the correct version of DCW to be released.
  - [x] `DCW_DATE` sets the correct release date.
- [x] Run `make spotless` to clear out any old distribution files.
- [x] Run `make all` to make the dcw-gmt.nc file, create the tarball and zipfile, compute the MD5 checksum of the tarball, and create the dcw figure.
- [x] Run `place-gmt` to place the tarball on the gmt ftp (@meghanrjones or @pwessel).
- [x] Run `place-dcw` to place the zip file on the dcw ftp and website (@pwessel).
- [x] Create a new [GitHub release](https://github.com/GenericMappingTools/dcw-gmt/releases).
  - [x] Upload the tarbell.
  - [x] Add a description to the release.
  - [x] Add the MD5 checksum to the release notes.
- [x] Run `update-dataserver` to update the files on the GMT server using the GitHub release (@pwessel or @meghanrjones).

**Comment by meghanrjones** [comment]
@Esteban82 and @PaulWessel, what do you think for the timing on releasing the 2.0.2 patch release? Are there any remaining issues to be tackled first (e.g., https://github.com/GenericMappingTools/dcw-gmt/issues/38)?

**Comment by PaulWessel** [comment]
@Esteban82 can merge #38 I think, should have no visual effect on results.

**Comment by Esteban82** [comment]
> @Esteban82 and @PaulWessel, what do you think for the timing on releasing the 2.0.2 patch release? Are there any remaining issues to be tackled first (e.g., https://github.com/GenericMappingTools/dcw-gmt/issues/38)?

No. The only thing to be fixed was the Russian islands (already done). 
I think it is better to make this release before #38. As Paul said it has no visual improvement and the release will have the same size. We later can, with no rush,  see #38.

**Comment by Esteban82** [comment]
I think we can go on with this. The changelog is updated.

**Comment by PaulWessel** [comment]
OK, I will work through this later today.  Have 3 zooms on the agenda and family visitors...

**Comment by PaulWessel** [comment]
Working through the release steps now.

**Comment by PaulWessel** [comment]
Hi @meghanrjones and @Esteban82, I have released DCW 2.0.2. Two questions though:

1. Not sure where MD5 numbers actually go for this?
2. Where did we place the update-data server script? I have already forgotten...

**Comment by meghanrjones** [comment]
1. I think this will be the first time we post the MD5 numbers. They could go in the release notes under the description.
2. It needs to get merged from https://github.com/GenericMappingTools/dcw-gmt/pull/29. There's currently a conflict with the config file that will need to be resolved before merging.

**Comment by PaulWessel** [comment]
OK, updated MD5 and fixed conflict in #29.  I think I got this to the point that it worked for me but not for you, so I should be able to execute it, yes?

**Comment by meghanrjones** [comment]
Great, thanks. Yes, it should work.

**Comment by PaulWessel** [comment]
I think all tasks have been completed. Thanks @Esteban82 and @meghanrjones.  Let me know if we forgot something (and can then add to the checklist).  I think with this release it is safe to work on the 2.1.0 version which will require the next GMT release to take advantage of the features.

**Comment by meghanrjones** [comment]
Great, thanks Paul and Federico!

**Comment by seisman** [comment]
Can you also provide the sha256sum? It's used in many other distributors like conda-forge and homebrew.
