### ISSUE TITLE
Move island from NE to DE

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/dcw-gmt#45]
From todays GMT contributor session: Extract data for Netherlands Segment 15 Borkum Island wrong in NL (wrong side of marine boundary), should be in DE polygon instead:

```
#6.74505378759    53.5751603042
#6.75732205829    53.5699026983
#6.75466786511    53.5664852545
#6.74735408835    53.5628049304
#6.74316636133    53.5680625363

```

I will have a look, @Esteban82

**Comment by Esteban82** [comment]
Closed by #46.
