### ISSUE TITLE
Åland islands

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#54]
I make this map of the  [Åland islands](https://en.wikipedia.org/wiki/%C3%85land) which is an autonomous region of Finland with its own ISO code (AX).  I see that there is a superposition between the dcw polygons (the islands paint in purple). 

I don't know if we should:
1. leave that way (like an special state within Finland like the states of the biggest 8 countries).
2. separate them from Finland (like some special territories like Puerto Rico and Svalbard and Jan Mayen). 

I think that all depend on what the users expects when they used `FI.txt.`

` gmt coast -B -png FIN -RAX -EAX+gred -EFI+gblue@60 -JM10`

![FIN](https://user-images.githubusercontent.com/17908951/149444208-aa899c1c-1817-4b02-85dd-8088b576d272.png)

**Comment by PaulWessel** [comment]
I think most would expect Åland to be plotted as part of Finland, Those few who have issues with that are probably not using GMT to begin with.  So I think we can safely leave things as they are here.

**Comment by Esteban82** [comment]
Ok. Perfect.
