### ISSUE TITLE
Release dcw 2.1.0

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/dcw-gmt#58]
**Version**:  2.1.0

**Scheduled date**: JAN 16, 2022

**Before release**:

- [x] Check the [changelog](https://github.com/GenericMappingTools/dcw-gmt/blob/master/ChangeLog).
- [x] Check the settings in [config.mk](https://github.com/GenericMappingTools/dcw-gmt/blob/master/config.mk).
  - [x] `GMT_VERSION` sets the correct minimum required GMT version.
  - [x] `DCW_VERSION` sets the correct version of DCW to be released.
  - [x] `DCW_DATE` sets the correct release date.
- [x] Run `make spotless` to clear out any old distribution files.
- [x] Run `make all` to make the dcw-gmt.nc file, create the tarball and zipfile, compute the MD5 checksum of the tarball, and create the dcw figure.
- [x] Run `place-gmt` to place the tarball on the gmt ftp (@meghanrjones or @pwessel).
- [x] Run `place-dcw` to place the zip file on the dcw ftp and website (@pwessel).
- [x] Create a new [GitHub release](https://github.com/GenericMappingTools/dcw-gmt/releases).
  - [x] Upload the tarball.
  - [x] Add a description to the release.
  - [x] Add the MD5 checksum and sha256sum to the release notes.
- [x] Run `update-dataserver` to update the files on the GMT server using the GitHub release (@pwessel or @meghanrjones).
- [x] Update the dcw version in the [downloads](https://github.com/GenericMappingTools/website/blob/master/download/index.rst) section of the website.

**Comment by PaulWessel** [comment]
All done, please try to get the new version from the approved places, @Esteban82.

**Comment by PaulWessel** [comment]
I successfully got the 2.1.0 file from the Releases page and installed locally here, so I think we are done.

**Comment by seisman** [comment]
There may be a permission issue for the tarball on the FTP site.

**Comment by sebastic** [comment]
> There may be a permission issue for the tarball on the FTP site.

There are:
```
ftp> ls -l
227 Entering Passive Mode (128,171,151,230,165,19)
150 Data connection accepted from 82.94.42.6:43646; transfer starting.
-rw-r--r--   1 ftpuser  ftpusers  21917782 Oct 23  2013 dcw-gmt-1.0.21.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21912317 Oct 24  2013 dcw-gmt-1.0.21.zip
-rw-r--r--   1 ftpuser  ftpusers  21074554 Nov  1  2013 dcw-gmt-1.1.0.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21070816 Nov  1  2013 dcw-gmt-1.1.0.zip
-rw-r--r--   1 ftpuser  ftpusers  21119595 Feb 10  2014 dcw-gmt-1.1.1.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21111384 Feb 10  2014 dcw-gmt-1.1.1.zip
-rw-r--r--   1 ftpuser  ftpusers  21110744 Sep  1  2015 dcw-gmt-1.1.2.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21107749 Sep  1  2015 dcw-gmt-1.1.2.zip
-rw-r--r--   1 ftpuser  ftpusers  21118460 Jan 21  2018 dcw-gmt-1.1.3.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21109047 Jan 21  2018 dcw-gmt-1.1.3.zip
-rw-r--r--   1 ftpuser  ftpusers  21117179 Jun 28  2018 dcw-gmt-1.1.4.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21107570 Jun 28  2018 dcw-gmt-1.1.4.zip
-rw-r--r--   1 ftpuser  ftpusers  21104029 Apr  7  2021 dcw-gmt-2.0.0.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21094270 Apr  7  2021 dcw-gmt-2.0.0.zip
-rw-r--r--   1 ftpuser  ftpusers  21960666 Nov 18 17:24 dcw-gmt-2.0.1.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21953019 Nov 18 17:24 dcw-gmt-2.0.1.zip
-rw-r--r--   1 ftpuser  ftpusers  21992052 Dec 15 11:42 dcw-gmt-2.0.2.tar.gz
-rw-r--r--   1 ftpuser  ftpusers  21984308 Dec 15 11:42 dcw-gmt-2.0.2.zip
-rw-------   1 ftpuser  ftpusers  21994257 Jan 15 10:56 dcw-gmt-2.1.0.tar.gz
-rw-------   1 ftpuser  ftpusers  21988364 Jan 15 10:56 dcw-gmt-2.1.0.zip
226 Listing completed.
ftp> get dcw-gmt-2.1.0.tar.gz
local: dcw-gmt-2.1.0.tar.gz remote: dcw-gmt-2.1.0.tar.gz
227 Entering Passive Mode (128,171,151,230,155,144)
553 Permission denied.
```

**Comment by PaulWessel** [comment]
Some things never change....
Should be OK now, thanks.
