### ISSUE TITLE
Add Norwegian counties

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/dcw-gmt#69]
I would like to add the Norwegian counties to DCW based on https://en.wikipedia.org/wiki/ISO_3166-2:NO.

Any guidelines how to do it?

**Comment by Esteban82** [comment]
Do you mean besides the info in [CONTRIBUTING.md](https://github.com/GenericMappingTools/dcw-gmt/blob/master/CONTRIBUTING.md)?

**Comment by Esteban82** [comment]
The data should have a format like this with 6 digits separated by a whitespace.

```
> angola 0
11.768336 -16.799326
11.764045 -16.799137
11.760199 -16.795959
11.756536 -16.787502
11.734854 -16.741121
11.719118 -16.692846
11.708150 -16.667934
11.699504 -16.636806
```

**Comment by anbj** [comment]
I think that gets me started. Thanks @Esteban82.

**Comment by joa-quim** [comment]
Sorry, but I don't think we should start adding more data to DCW. All countries have internal administrative boundaries. Image that we were to add that to all countries. Use GADM for that.

... and just to tease Andreas
https://www.generic-mapping-tools.org/GMT.jl/dev/gallery/GADM/gadm/

**Comment by Esteban82** [comment]
I was thinking the same. Maybe @anbj could create his own local version of the DCW collection with Norwegian counties.

**Comment by Esteban82** [comment]
> All countries have internal administrative boundaries. Image that we were to add that to all countries.

I agree that if would be a lot of work to add all the countries. So, if someone pretends that we make the had work, I would say no. But, if the had work will be make by someone else, why not?

**Comment by joa-quim** [comment]
We are not in the business of distributing data. For this particular purpose someone else is, GADM.
I  don't want to see DCW grow to the hundreds MB size and would not include it in the Windows installer.

**Comment by anbj** [comment]
My thought was to do this for fun; I didn't think it would take more than a couple of hours max, but maybe not.

I know you've been discussing *the new thing* so maybe this could wait. Thanks for input!
