### ISSUE TITLE
Changes of China's state/province codes

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/dcw-gmt#7]
DCW currently uses 2-digit codes for states/provinces in China (e.g., CN-11 for Beijing). As per the [ISO 3166-2:CN wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:CN), the codes were changed to more readable and consistent 2-char codes (e.g., CN-11 changes to CN-BJ) since 2017.

Can we make the changes in the DCW 2.0.0 release? Ideally, it should be backward compatible, but it's not a big issue as we're releasing DCW v2.0.0.

**Comment by PaulWessel** [comment]
Yes, we can do that for 2.0.0.  I am not sure if it is worth it to maintain backwards compatibility though.

**Comment by seisman** [comment]
I don't think it's worth the efforts to maintain backward compatibility. 

Perhaps GMT can report errors when codes like `CN.11` are used for DCW>=2.0.0?

**Comment by PaulWessel** [comment]
Actually, it was pretty easy to implement, see #3911.

**Comment by PaulWessel** [comment]
Closed via GMT update.
