### ISSUE TITLE
Warning plotting -E=AS

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/dcw-gmt#71]
```
$ gmt pscoast  -R-180/180/-90/90 -Jj1:100000000  -E=AS+p -pdf test
coast [ERROR]: Failure while getting ID for variable HK_length in /home/anbj/gmt/share/dcw/dcw-gmt.nc!
```

**Comment by Esteban82** [comment]
I test it and I have no problem ( got a map of Asia). Could you check again?

**Comment by anbj** [comment]
Getting the same;

```
$ gmt pscoast  -R-180/180/-90/90 -Jj1:100000000  -E=AS+p -pdf test
coast [ERROR]: Failure while getting ID for variable HK_length in /home/anbj/gmt/share/dcw/dcw-gmt.nc!
```

```
gmt --show-dcw
2.1.0
```

**Comment by PaulWessel** [comment]
I can confirm I get the same thing.  Need to debug to see what triggers it.  I can tell using **ncdump** there is no _HK_length_ variable anymore, only CNHK_length:

```
ncdump -h dcw-gmt.nc  | grep HK_length
	CNHK_length = 1019 ;
	ushort CNHK_lon(CNHK_length) ;
	ushort CNHK_lat(CNHK_length) ;
```

So maybe a side effect of recent changes?

**Comment by anbj** [comment]
I'm on

```
$ gmt --version
6.4.0_e4bc09a_2022.03.17
```

**Comment by PaulWessel** [comment]
Maybe @Esteban82 remembers this, but we clearly have this in the data files:

```
dcw-countries.txt:AS HK Hong Kong
dcw-states.txt:CN HK Xianggang (Hong Kong)
```

So there must be confusion between HK the country and HK the province of China.  It cannot be both I think.

**Comment by Esteban82** [comment]
I remer

> Maybe @Esteban82 remembers this, but we clearly have this in the data files:
> 
> ```
> dcw-countries.txt:AS HK Hong Kong
> dcw-states.txt:CN HK Xianggang (Hong Kong)
> ```
> 
> So there must be confusion between HK the country and HK the province of China. It cannot be both I think.

I remember deleted HK and MO as a country ( #56  ) .

**Comment by Esteban82** [comment]
I see. By error, I deleted TW.txt instead of HK.txt.

Later I will fix it.

**Comment by Esteban82** [comment]
Yes. I could use add the continental sector of Portugal, Spain, Costa Rica and Ecuador in dcw-collections for 2.1.1.
