### ISSUE TITLE
Release v2.1.1 or v2.2.0?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/dcw-gmt#76]
There are a few commits that fix bugs in DCW. Perhaps we should make the new release before GMT v6.4.0.

**Comment by PaulWessel** [comment]
Yes I agree. @Esteban82, anything we should do before releasing gmt-dcw?

**Comment by Esteban82** [comment]
No, the only thing I can think of is the [last comment of issue #30](https://github.com/GenericMappingTools/dcw-gmt/issues/30#issuecomment-1020798317).  Not very important. We can leave it as it is.

**Comment by PaulWessel** [comment]
This should be 2.1.1 since 2.1 introduced the collections and this is just a tiny cleanup, I think.  OK for me to push this out once I get back to Oxford?

**Comment by seisman** [comment]
The new release will be tracked in https://github.com/GenericMappingTools/dcw-gmt/issues/78
