### ISSUE TITLE
Release dcw 2.1.1

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/dcw-gmt#78]
**Version**:  2.1.1

**Scheduled date**: May 20, 2022

**Before release**:

- [x] Check the [changelog](https://github.com/GenericMappingTools/dcw-gmt/blob/master/ChangeLog).
- [x] Check the settings in [config.mk](https://github.com/GenericMappingTools/dcw-gmt/blob/master/config.mk).
  - [x] `GMT_VERSION` sets the correct minimum required GMT version.
  - [x] `DCW_VERSION` sets the correct version of DCW to be released.
  - [x] `DCW_DATE` sets the correct release date.
- [x] Run `make spotless` to clear out any old distribution files.
- [x] Run `make all` to make the dcw-gmt.nc file, create the tarball and zipfile, compute the MD5 checksum of the tarball, and create the dcw figure.

**Release**

- [x] Run `place-gmt` to place the tarball on the gmt ftp (@meghanrjones or @pwessel).
- [x] Run `place-dcw` to place the zip file on the dcw ftp and website (@pwessel).
- [x] Create a new [GitHub release](https://github.com/GenericMappingTools/dcw-gmt/releases).
  - [x] Upload the tarball.
  - [x] Add a description to the release.
  - [x] Add the MD5 checksum and sha256sum to the release notes.
- [x] Run `update-dataserver` to update the files on the GMT server using the GitHub release (@pwessel or @meghanrjones).
- [x] Update the dcw version in the [downloads](https://github.com/GenericMappingTools/website/blob/master/download/index.rst) section of the website.

**3rd-party update**

**More volunteers needed!** Please let us know if you volunteer to help to maintain dcw-gmt in these 3rd-party tools.

- [x] Update [conda-forge feedstock](https://github.com/conda-forge/dcw-gmt-feedstock) (@seisman) (https://github.com/conda-forge/dcw-gmt-feedstock/pull/10)
- [x] Update [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gmt.rb) (@seisman) (https://github.com/Homebrew/homebrew-core/pull/101918)
- [x] Update the builtin dcw-gmt version in the Windows installers (@joa-quim)

**Comment by PaulWessel** [comment]
What is the procedure for editing the language in the checklist (I want to clarify a few things)?

**Comment by seisman** [comment]
The original checklist template is here: https://github.com/GenericMappingTools/dcw-gmt/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md

**Comment by PaulWessel** [comment]
I have a draft GitHub release - looks OK @seisman ?

**Comment by meghanrjones** [comment]
LGTM

**Comment by seisman** [comment]
I just downloaded the tar.gz tarball from https://github.com/GenericMappingTools/dcw-gmt/releases/tag/2.1.1. The sha256sum value is d4e208dca88fbf42cba1bb440fbd96ea2f932185c86001f327ed0c7b65d27af1, different from the one you gave in the release page.

**Comment by PaulWessel** [comment]
Suggestions for solution?

**Comment by meghanrjones** [comment]
> Suggestions for solution?

Can you double check the hash of the source file on the UH computer and the oxford computer to tell whether https://github.com/GenericMappingTools/dcw-gmt/issues/78#issuecomment-1131932372 accurately describes the mix-up? If that's the case, the solution is to edit the release notes with the correct hash.

**Comment by PaulWessel** [comment]
I have updated the release page with correct values.

**Comment by joa-quim** [comment]
Already done.
