### ISSUE TITLE
Zenodo for DCW-GMT?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#84]
I just wonder if would be a good idea to create a repository in Zenodo for the DCW-GMT? 

I know that this page exist 
https://www.soest.hawaii.edu/pwessel/dcw/

**Comment by PaulWessel** [comment]
Yes, probably.  Same for GSHHG I presume.  The UH page could then link to the tarball on Zenodo.

**Comment by Esteban82** [comment]
Do you want me to try to do it?

**Comment by PaulWessel** [comment]
Sure, you can see some relevant meta data from the GMT Zenodo entry (NSF support) and then you can add anything else you want to see.

**Comment by Esteban82** [comment]
In the Zenodo page, should I a add this right?

Funded by US National Science Foundation grants OCE-1558403 and EAR-1829371.

**Comment by PaulWessel** [comment]
yes, that would be good, thanks!

**Comment by Esteban82** [comment]
Is there any way that I could share a preview of the zenodo page? This is page but I don't know if you could access.
https://zenodo.org/deposit/6823057

**Comment by PaulWessel** [comment]
Says I dont have enough permission.  So you would have to add me somehow.

**Comment by Esteban82** [comment]
Paul, I try to give permission. I couldn't find how. I write them but they haven't answer my yet. 

So I will share some screenshots with the info for **DCW 2.1.1**. 

I couldn't find the OCE grant so I added in Aditional Notes,  Let me know is everithing is ok. 


![1](https://user-images.githubusercontent.com/17908951/179231652-4972450a-ed68-4f3b-9650-1132999cfab5.png)
![2](https://user-images.githubusercontent.com/17908951/179231656-6e72bd6e-2aac-4a93-a3a8-7108911db786.png)
![3](https://user-images.githubusercontent.com/17908951/179231658-bd6a45c4-01f7-4b1b-b844-d0ccd6d7018c.png)
![4](https://user-images.githubusercontent.com/17908951/179231659-46a84f54-cedc-43eb-89ca-93d75c21556e.png)
.

**Comment by seisman** [comment]
> Paul, I try to give permission. I couldn't find how.

That's a known limitation of zenodo. See https://github.com/GenericMappingTools/pygmt/issues/601 for related discussions.

**Comment by Esteban82** [comment]
@PaulWessel could you look at the screen captures? 
I asked and there is no way to share the repository. I should try seisman suggestion.

**Comment by PaulWessel** [comment]
Yes, sorry - let this slip.  It looks fine, @Esteban82.

**Comment by Esteban82** [comment]
Just published.
https://zenodo.org/record/6823057

**Comment by seisman** [comment]
Do you think we should add the zenodo DOI and the citation information to the README file?

**Comment by anbj** [comment]
Isn't this done?

**Comment by Esteban82** [comment]
Yes.
