### ISSUE TITLE
Building dcw - problems

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/dcw-gmt#86]
First time attempting to build dcw.

Some issues;

* ``make build-dcw`` fails:

```
$ make build-dcw
time bash DCW2singleshortnc.sh 2.1.1 6.1.1
make: time: Command not found
make: *** [Makefile:122: dcw-gmt.nc] Error 127
```

Very strange - why is `time` not allowed to be prefixed?
Remove `time` and no problems occur.

```
$ bash --version
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
```

* What are the deps?
```
[...]
SR : Converting
UY : Converting
VE : Converting
Generate netCDF4...
DCW2singleshortnc.sh: line 163: ncgen: command not found
DCW2singleshortnc.sh: line 164: nccopy: command not found
```

Based on searching, ``netcdf-bin`` seems to be it (Debian).

**Comment by PaulWessel** [comment]
Also, I think @Esteban82 might be running this on Linux and he has not complained.

**Comment by PaulWessel** [comment]
Apparently, I get /usr/bin/time but you get the poor bash-built in time which is not the same [https://stackoverflow.com/questions/385408/get-program-execution-time-in-the-shell].

**Comment by Esteban82** [comment]
> Also, I think @Esteban82 might be running this on Linux and he has not complained.

Yes, I have used Ubuntu 20.04 without any problem.

**Comment by anbj** [comment]
Installed *time* and works fine. This is on Debian 11.
