### ISSUE TITLE
Add states for Norway

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/dcw-gmt#88]
I know, you've said it many times; don't spend time on dcw. But, I want ot scratch my own itch, and it's fun to learn the plumbing of dcw. So I would like to add the 'states' (counties) of Norway. Some questions;

* do the county lines have to be closed? I've looked at *DCW2singleshortnc.sh* and based on that, my guess is they do.
* the lines/polygons extend ~12 nautical miles off the coast ('territorial limit'). Is that ok? Or do they have to be clipped to the country polygon?
* Any place to document source and year the data is from?

**Comment by PaulWessel** [comment]
- Yes, all entries have to be fully closed polygons, meaning shared borders appear twice.
- Have to be clipped at coast line and coastline needs to be added as part of the border.
- Can add information to the index.html file, the README.md and/or add another text file with source info.

**Comment by anbj** [comment]
And *clipped at the coast line* means, in my case, clipped to the (exact) polygon I get when I do a `gmt pscoast -ENO -M`?

**Comment by PaulWessel** [comment]
Yes, I guess it should match the DCW NO coastline segments.

**Comment by PaulWessel** [comment]
Wow, that was fast.  You can certainly set the version to 2.1.2 now since we released 2.1.1.  The date is unknown so just leave.
And yes add an entry in the changelog explaining what is new - it is usually a relatively short quick summary as you can see.

**Comment by seisman** [comment]
Just a quick comment: because PR #89 adds more dataset into dcw, rather than fixing wrong boundaries in dcw, perhaps the next version should be 2.2.0, not 2.1.2.

**Comment by PaulWessel** [comment]
OK, makes sense - let's do that @anbj.  @Esteban82, would you have time for a look at this PR? I am a bit over-booked today.

**Comment by anbj** [comment]
Alright, 2.2.0 it is. Pushed.

**Comment by Esteban82** [comment]
I see that your data has more than 6 decimals. Could you reduce it to 6? 

Also, I think that if tou could include the name of the county on the header could be helpfull.

```
# @P
4.88862477348 59.3180832115
4.89307076417 59.3194954416
```
