### ISSUE TITLE
Add Bjørnøya to DCW code SJ

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/dcw-gmt#90]
Bjørnøya is missing from the dataset and I would like to add it.
-- I know, I know - "don't spend time on this dataset".
Well, the DCW dataset is so useful, I would like to spend time on it.

So - do I just append a new 'bjørnøya'-segment to `SJ.txt`, ala

```
> bjørnøya 0
-8.137269 71.146187
-8.094492 71.147224
```

?

**Comment by joa-quim** [comment]
Don't know the polygon but I think you shouldn't mix gshhg and DCW polygons. They use different datum.

**Comment by anbj** [comment]
Okay, thanks @joa-quim.

**Comment by anbj** [comment]
Do you happen to know which datum?

**Comment by joa-quim** [comment]
GDHHG is 70ies stuff digitized by CIA so possibly ED50 on many European data. Who knows by now.

**Comment by anbj** [comment]
ED50 again.. bah. Alright. Not sure what to use then.

**Comment by Esteban82** [comment]
@anbj can I close this?

**Comment by anbj** [comment]
Please do. I tried this, got into trouble and never started again. May do it at a later time.

**Comment by anbj** [comment]
Reopening - ambitions to try this again.

**Comment by anbj** [comment]
I'm running into the same problem I did the last time.

I've added some 10 new segments to ``SJ.txt``:

```
> bjornoya 0
19.000000 74.506020
18.997559 74.505394
18.992447 74.505394
18.991104 74.505776
[...]
> bjornoya 1
19.000000 74.367895
19.000015 74.367895
19.001312 74.367498
19.001190 74.366690
19.003632 74.365805
19.003723 74.363302
19.005051 74.362921
19.007584 74.362890
[...]
```

It builds fine, but when I dump the new code for testing it goes complete haywire.
It starts fine, but then it spews out out empte segments ad infinitum::

```
$ gmt coast -ESJ -M | head
>  Svalbard and Jan Mayen Segment 0
11.5072777964	79.8658471466
11.5293670311	79.8611136805
11.5150739969	79.8446228954
11.4812904614	79.8429432784
11.449455976	79.8545479049
11.4767426777	79.8629459899
11.5072777964	79.8658471466
>  Svalbard and Jan Mayen Segment 1
11.5605518331	79.8595867559
[...]
-8.21061264385	71.1353506806
-8.16383544083	71.1429853033
-8.16383544083	71.1429853033
-8.13719842245	71.1461918448
>  Svalbard and Jan Mayen Segment 115
>  Svalbard and Jan Mayen Segment 116
>  Svalbard and Jan Mayen Segment 117
>  Svalbard and Jan Mayen Segment 118
>  Svalbard and Jan Mayen Segment 119
>  Svalbard and Jan Mayen Segment 120
>  Svalbard and Jan Mayen Segment 121
>  Svalbard and Jan Mayen Segment 122
>  Svalbard and Jan Mayen Segment 123
>  Svalbard and Jan Mayen Segment 124
>  Svalbard and Jan Mayen Segment 125
>  Svalbard and Jan Mayen Segment 126
>  Svalbard and Jan Mayen Segment 127
>  Svalbard and Jan Mayen Segment 128
>  Svalbard and Jan Mayen Segment 129
>  Svalbard and Jan Mayen Segment 130
>  Svalbard and Jan Mayen Segment 131
>  Svalbard and Jan Mayen Segment 132
>  Svalbard and Jan Mayen Segment 133
>  Svalbard and Jan Mayen Segment 134
>  Svalbard and Jan Mayen Segment 135
[...]
>  Svalbard and Jan Mayen Segment 999
>  Svalbard and Jan Mayen Segment 1000
>  Svalbard and Jan Mayen Segment 1001
>  Svalbard and Jan Mayen Segment 1002
```

What am I missing?!

**Comment by joa-quim** [comment]
Don't know. You perhaps use a tool that shows the nc contents to try to find out if the new data was correctly inserted.

**Comment by anbj** [comment]
Yes, thanks for the tip. I'll just do some trial-and-error.

**Comment by anbj** [comment]
Tried again, and now it works. _Maybe_ I didn't close the polygons (first point != last point).

**Comment by anbj** [comment]
> Don't know. You perhaps use a tool that shows the nc contents to try to find out if the new data was correctly inserted.

@joa-quim any recommended tool for inspecting nc files? I tried **ncview**, but looks like this only works with nc files ‘containing grids’.

**Comment by joa-quim** [comment]
Andreas, I use this old but very nice [HDFexplorer](https://www.space-research.org/hdf_explorer/hdf_explorer.htm) Windows program. But there is also the [HDFview](https://www.hdfgroup.org/downloads/hdfview/) that being in (shitty) Java should run everywhere.

**Comment by anbj** [comment]
Thanks! I’ll try those.

**Comment by anbj** [comment]
Won't touch shitty Java until I absolutely have to. And looks like HDFexplorer requires a purchased license? Will see if there are alternatives.

**Comment by joa-quim** [comment]
Forgot to mention. The HDFexplorer accepts any login/passwd. At least mine. Far memories tell me that we had to ask a log/pass to the developer. Anyway, it's a small proggy (12 MB zipped). Get it from https://fct-gmt.ualg.pt/lixo/HDF_Explorer.zip

**Comment by anbj** [comment]
Thanks! Downloaded the zip, and able to run and use the executable within.

**Comment by anbj** [comment]
@joa-quim Do you know if I'm allowed to use non-ascii in segment headers? E.g. ``> bjørnøya``?

**Comment by joa-quim** [comment]
I suspect it is not a good idea. Recently I tried to read a file with non-ascii characters and it failed.

**Comment by anbj** [comment]
Thanks. Better safe than sorry.
