### ISSUE TITLE
Inconsistent border between DE and PL

### ISSUE THREAD

**Issue by geophysx** [GenericMappingTools/dcw-gmt#92]
The Eastern-most border of Germany (DE) is inconsistent with the neighboring Polish (PL) subset near 51.2°N: for several entries in the DE subset, the DE border (wrongly) strikes exactly North-South, where it should rather stretch out to the max lon  of Germany at >15°E. Five entries do have identical Longitude 14.9998576184, two are even completely identical. At the same time, the PL subset draws correctly several km further East along the river Neisse. Several dozens of square-km are affected, as the DE border seems simply 'cut' at 15°E.

When I analysed this, I was working with ASCII tables imported into Matlab that were extracted via:
`gmt pscoast -E$1 -M -V > $FILE`
where $1 is the country code like 'DE' or 'PL'. 
The same can be seen when plotting both DCW sets on a map with `gmt coast`, without explicitly extracting coordinates to a table beforehand. The issue seems to be persistent in DCW-GMT 2.1.1 and older versions. 

PC
* Operating system: OpenSUSE Leap 15.4 x86_64
* DCW version: 2.1.1 (and older, e.g. 1.1.4)
* GMT version (`gmt --version`): 6.1.1

Cheers,
Ben

Attached is a figure made with
```
#!/bin/sh
gmt begin DE_PL_inconsist png
gmt basemap -R14/16/50.75/51.5 -JM15c -B+gsnow4
gmt coast -EDE+glightgreen -t25
gmt coast -EPL+glightred -t25
gmt basemap -Bag.5 -BWeSn+t"DCW no-man's-land btw DE&PL"
gmt end show
```
![DE_PL_inconsist](https://user-images.githubusercontent.com/122893576/213015306-f5feea9e-5829-4c23-ab37-55e8baaba19c.png)

**Comment by joa-quim** [comment]
Hi, this is a recurrent issue (DCW and/or GSHHG borders correctness) and we are well aware of that. But on the other hand it has long be decided to not try to fix these **endless** cases. People that really need better borders should use other data sources.

**Comment by geophysx** [comment]
Duly noted. Dunno what to say, haha, but I understand what you are saying. Kind of sad, when better (correct) data obviously does exist in the same data set, for the same border. It is not that the subsets are inconsistent against each other, it is that DE is simply wrong here over a significant stretch. As I am lacking the technical background how DCW-GMT borders actually are generated from various sources, I am going to accept that you will have had good reasons for the decision.

I will now try to combine DE and PL into one useful vector set myself instead, based on (tm) DCW-GMT. I was happy to finally work with GMT after some time again, you will not lose me so quickly now ;-) 

Thank you for the quick response, though. I appreciate that. I guess this issue can be closed then, if there isn't anything I could do to still let it live and hope for(?)

**Comment by joa-quim** [comment]
> you will have had good reasons for the decision.

Just plain and simple lack of manpower to attend to the endless cases where this old dataset show ... its age.
Have a look to the GADM data.

**Comment by anbj** [comment]
Just to be clear; the green area should fill the small gray pocket in your original post?

**Comment by geophysx** [comment]
That is correct. The German territory (green) in the plotted data is missing its area east of 15 degrees East here. Where it should rather be the way the Polish (red) selection draws. The most Eastern point of DE would be approx. E15°02'30".

Did not expect to touch this after 15 months again :-)
Thx to @joa-quim for the useful GADM tip, btw!

**Comment by anbj** [comment]
I bet that someone thought that all of DE was west of 15E (and it almost is; the gray void is about 25 km2), so they did a cut at 15E.

It should be easy to fix.

**Comment by anbj** [comment]
Fixed. Will do a PR soon.
![DE_PL_inconsist](https://github.com/GenericMappingTools/dcw-gmt/assets/29237824/f20c81f7-7726-411d-a909-455fdc2855e4)

**Comment by anbj** [comment]
Closing. Please re-open if problems.
